[manager]
ratio = [1, 4, 3]
show_hidden = true
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "size_and_mtime"
show_symlink = true
scrolloff = 10
mouse_events = ["click", "scroll"]
# title_format = "Yazi: {cwd}"

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""
# image_delay = 30
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]
